var base = require('./Base'),
    config = require('./Config'),
    product = require('./Product'),
    payment = require('./Payment'),
    shipping = require('./Shipping');

exports.BaseRequest = base.BaseRequest;
exports.BaseResponse = base.BaseResponse;
exports.ConfigValueType = config.ConfigValueType;
exports.SimpleConfigItem = config.SimpleConfigItem;
exports.ConfigItem = config.ConfigItem,
exports.ConfigItemListItem = config.ConfigItem,
exports.UserConfig = config.UserConfig;
exports.AddNewUserRequest = config.AddNewUserRequest;
exports.AddNewUserResponse = config.AddNewUserResponse;
exports.SaveUserConfigRequest = config.SaveUserConfigRequest;
exports.UserConfigResponse = config.UserConfigResponse;
exports.Product = product.Product;
exports.ProductsRequest = product.ProductsRequest;
exports.ProductsResponse = product.ProductsResponse;
exports.ProductInventory = product.ProductInventory,
exports.ProductInventoryUpdateRequest = product.ProductInventoryUpdateRequest,
exports.ProductInventoryUpdateResponse = product.ProductInventoryUpdateResponse,
exports.ProductInventoryError = product.ProductInventoryError,
exports.PaymentTag = payment.PaymentTag;
exports.PaymentTagResponse = payment.PaymentTagResponse;
exports.ShippingTag = shipping.ShippingTag;
exports.ShippingTagResponse = shipping.ShippingTagResponse;